version: '3.8'
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "3000:3000"
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    networks:
      - mynetwork

networks:
  mynetwork:
