version: '3.8'
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "3000:80"
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      - MONGO_URL=mongodb://rawlin:rawlin@mongodb:27017/mydb?authSource=admin
    networks:
      - mynetwork
    
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rawlin
      - MONGO_INITDB_ROOT_PASSWORD=rawlin
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - myvolume:/data/db

networks:
  mynetwork:
volumes:
  myvolume:
